name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{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}}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign to One Project
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/users/frederikgantriis/projects/7'
